# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving:serving-client
    ports:
        - "8080:8080"
    environment:
        COMET_ML_KEY: ${COMET_ML_KEY}
  jupyter:
    build:
      context: ./
      dockerfile: ./Dockerfile.jupyter
      args:
        JUPYTER_PORT: 8888
    environment:
        JUPYTER_PORT: 8888
        COMET_ML_KEY: ${COMET_ML_KEY}
    image: ift6758/jupyter:game-dashboard
    ports:
      - "8888:8888"
      

     
